### ISSUE TITLE
onPress TouchableOpacity triggers more than once on AndroidTv

### ISSUE THREAD

**Issue by Sarvarr** [react-native-community/react-native-tvos#110]
"react": "16.11.0",
"react-native": "npm:react-native-tvos@0.63.1-1",
my code:
<TouchableOpacity style={[styles.container, props.style]} onPress={()=>{
        console.log("clicked")
    }}>
        <Text>
            CLICK
        </Text>
    </TouchableOpacity>

**Comment by Sarvarr** [comment]
[](https://github.com/facebook/react-native/issues/25979#issuecomment-575564756)

**Comment by mehthabux** [comment]
@Sarvarr Add `Platform.OS !== 'android'` in TvTouchable.js file

replace the contructor inside TvTouchable.js with 

`constructor(component: any, config: TVTouchableConfig) {
    invariant(Platform.isTV, 'TVTouchable: Requires `Platform.isTV`.');
    this._tvEventHandler = new TVEventHandler();
    this._tvEventHandler.enable(component, (_, tvData) => {
      tvData.dispatchConfig = {};
      if (ReactNative.findNodeHandle(component) === tvData.tag) {
        if (tvData.eventType === 'focus') {
          config.onFocus(tvData);
        } else if (tvData.eventType === 'blur') {
          config.onBlur(tvData);
        } else if (tvData.eventType === 'select' &&  Platform.OS !== 'android') {
          if (!config.getDisabled()) {
            config.onPress(tvData);
          }
        }
      }
    });
  }`

**Comment by dlowder-salesforce** [comment]
Looks like this is ok to close.... feel free to reopen if there are other issues :)
