### ISSUE TITLE
Build failed : Flipper-Glog-tvOS

### ISSUE THREAD

**Issue by dies-iris** [react-native-community/react-native-tvos#112]
## Description
I have followed the steps described in the repository to start a new project.
Builds of new tvOS app or RNtester app fail every time due to a Flipper-glog issue.
Tried downgrading Xcode from 12 to 11.7, reinstalling pods and node modules.

## React Native version:
System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 2.2 AI-145.3537739
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.13 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: Not Found
    react-native-tvos:  0.63.1-1 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npm install -g @react-native-community/cli
2. react-native init TestApp --template=react-native-tvos@latest
3. cd TestApp && react-native run-ios  --simulator "Apple TV" --scheme "TestApp-tvOS"

## Expected Results
Build succeed and run on apple device or emulator

## Snack, code example, screenshot, or link to a repository:

Running react-native run-ios  --simulator "Apple TV" --scheme "TestApp-tvOS" in Terminal gives this :
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/tvapps/Library/Developer/Xcode/DerivedData/TestApp-eskrewdzxzqictgltvcegelviobk/Build/Intermediates.noindex/Pods.build/Debug-appletvsimulator/Flipper-Glog-tvOS.build/Objects-normal/x86_64/vlog_is_on.o /Users/tvapps/Desktop/TestApp/ios/Pods/Flipper-Glog/src/vlog_is_on.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

while in Xcode : 

<img width="1063" alt="Capture d’écran 2020-09-25 à 14 17 02" src="https://user-images.githubusercontent.com/51315734/94266237-21e40880-ff3a-11ea-80e7-73610a5ba178.png">

I would be thankful for your feedback.

**Comment by dlowder-salesforce** [comment]
I don't reproduce this issue with Xcode 12.  I followed your exact steps, and the app builds and runs as expected.

**Comment by dlowder-salesforce** [comment]
@dies-iris I wasn't able to repro this with the latest Xcode 12, so I'm closing it for now.  If you still see it in a new project, please feel free to reopen this and attach a link to the project so I can investigate.
