### ISSUE TITLE
react-native init command fails to find a correct version

### ISSUE THREAD

**Issue by dnicolson** [react-native-community/react-native-tvos#19]
The init command in the README fails due to not finding a matching version.

React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 431.88 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.1 - ~/.asdf/installs/nodejs/10.15.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.asdf/installs/nodejs/10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native-tvos: 0.60.4-6
    react-native: 0.61.1

## Steps To Reproduce

1. `npm i -g react-native react-native-tvos`
2. `react-native init TestApp --version=react-native@npm:react-native-tvos@latest`

Describe what you expected to happen:
The init command to successfully run.

The following is the output of the init command:
```
✖ Downloading template
error Error: Command failed: yarn add react-native@react-native@npm:react-native-tvos@latest
error Couldn't find any versions for "react-native" that matches "react-native@npm:react-native-tvos@latest"
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by dlowder-salesforce** [comment]
Step 1 in your repro steps is incorrect.  You should remove `react-native` and `react-native-tvos` from your global installs.  Then do `npm i -g react-native-cli`.

Also, when executing `react-native init`, do not do it inside a directory that is an existing npm project with react-native installed.
