### ISSUE TITLE
JSON value 'none' of type NSString cannot be converted to NSNumber message

### ISSUE THREAD

**Issue by projetsdiy** [react-native-community/react-native-tvos#21]
Hello. I created a new project with the latest version (react-native init testApp --version=react-native@npm:react-native-tvos@latest).

After installation, i ran pod install inside the ios folder

The App is correctly build but i have 2 error messages
JSON value 'dark-content' of type NSString cannot be converted to NSNumber 
JSON value 'none' of type NSString cannot be converted to NSNumber message

![Capture d’écran 2019-10-17 à 09 11 36](https://user-images.githubusercontent.com/5605142/66986571-72fb4380-f0bf-11e9-81d4-6ffdac641946.png)

Did i made a mistake during installation ? Thank you very much

### My config
* Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
* SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 27, 28
      Build Tools: 28.0.3
 * IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
 * npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native-tvos:  0.60.4-6

**Comment by dlowder-salesforce** [comment]
I don't reproduce this issue locally.  I would recommend that you move to Xcode 11.1 and iOS 13.1.x, and see if you still get an error.

**Comment by projetsdiy** [comment]
You're right ! No problem with XCode 11.1. Thank you very much and have a nice week end !

**Comment by dlowder-salesforce** [comment]
Excellent -- thanks for letting me know!! :)

**Comment by ArturasMi** [comment]
I'm actually having the same issue with react-native-tvos@0.60.4-6 on iPhone 8 simulator when trying to change status bar style _StatusBar.setBarStyle("light-content")_ . xCode version: 11.1

**Comment by dlowder-salesforce** [comment]
This seems to be fixed in react-native-tvos@0.61.2-0.

See https://github.com/facebook/react-native/issues/26619 for details.
