### ISSUE TITLE
Attempted to set a non-object key in a WeakMap with redux in a tvOS 13 project

### ISSUE THREAD

**Issue by projetsdiy** [react-native-community/react-native-tvos#27]
Hello, i've this error when i include redux in my tvOS project
Attempted to set a non-object key in a WeakMap
I've a blank screen after

## React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Memory: 20.27 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 27, 28
      Build Tools: 28.0.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native-tvos:  0.60.4-6

## Code to reproduce
```
import { createStore, combineReducers } from 'redux';

//Reducers
import testReducer from 'store/reducers/test';

const rootReducer = combineReducers({
  test:        testReducer,
});

export default function configureStore(initialState) {
  return createStore(
      rootReducer,
      initialState,
  );
}
```

In the app.js file
```
import configureStore from 'store/configureStore';
const store = createStore(SettingsReducer);
```

Thank you in advance

**Comment by dlowder-salesforce** [comment]
@projetsdiy thanks for the report! Can you provide all of the JS code for your test project?  Also, does the same error occur on RN core version 0.60.4?

**Comment by dlowder-salesforce** [comment]
Also, please provide your `package.json` so I can see all of the project dependencies.

**Comment by projetsdiy** [comment]
I think I found the origin of the problem. Part of the reducer code is shared with my android project. I save the user settings using the react-native-shared-preferences package ... and of course it was not installed on the tvOS project 🙃 really sorry for the loss of time. 
The debugging is a little longer on tvOS because when I run JS Debugger, the tvOS app crashes. Do you have the same problem?

**Comment by dlowder-salesforce** [comment]
I am not having any problem with the JS Debugger.
