### ISSUE TITLE
Clean `react-native init TestApp` produces errors for RCTView

### ISSUE THREAD

**Issue by tonycoco** [react-native-community/react-native-tvos#34]
There's an error in console, if dismissed it seems to work fine:

```
[error][tid:com.facebook.react.JavaScript] RCTView generated view config for validAttributes does not match native, missing: tvParallaxProperties isTVSelectable
```

Seems like just a few `validAttributes` need to be added.

React Native version:

```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 235.97 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /nodejs/12.10.0/bin/node
    npm: 6.10.3 - /nodejs/12.10.0/bin/npm
    Watchman: 4.9.0 - /watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native-tvos:  0.61.5-0
```

## Steps To Reproduce

1. `react-native init TestApp --version=react-native@npm:react-native-tvos@latest`
2. Build
3. Run in Simulator

**Comment by tonycoco** [comment]
Odd that it is fixed with me init'ing a new project with yarn now installed.

**Comment by ryanvanderpol** [comment]
hey, @tonycoco, sounds like you resolved this by starting a brand new project.  I'm running into this same error now and not in a position to start over... any idea how to fix it?

**Comment by tonycoco** [comment]
No idea, I nuked my project and started using TVML instead of ReactNative honestly.

**Comment by ryanvanderpol** [comment]
haha, ok, thanks.  yeah, can't blame you, this has been a nightmare so far.

**Comment by dlowder-salesforce** [comment]
@ryanvanderpol could you provide more details on your project and what react-native-tvos version you are using?

**Comment by ryanvanderpol** [comment]
@dlowder-salesforce happy to give you whatever you need cause this is driving me crazy.  If I hit the ESC key the error message goes away and the app seems to function fine but the error pops up every single time I make any change to the app.

here is a screenshot of the message I see:

![Screen Shot 2020-03-17 at 12 22 22 PM](https://user-images.githubusercontent.com/1936460/76877563-ff19be80-6849-11ea-823b-6a8576a576cc.png)

System info:
```
$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 27.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-23 | Android TV Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native-tvos:  0.61.5-0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

package.json:
```
{
  "name": "xxxx",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "lodash": "^4.17.15",
    "react": "16.9.0",
    "react-native": "npm:react-native-tvos@0.61.5-0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "7.8.7",
    "@babel/runtime": "7.8.7",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.4",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

what else would you like to know?

**Comment by dlowder-salesforce** [comment]
Hmm the issue definitely does not repro with a new project.  

Here's what I'd like you to do:

- Copy your project folder to a new directory
- Remove your RN application code (if it's proprietary and you don't want me to see it)
- Zip it up and put it in a dropbox where I can get it

I'm particularly interested in making sure that there are not multiple versions of react-native in node_modules, and making sure that the contents of node_modules/react-native/Libraries looks correct.

**Comment by brodybits** [comment]
In general I would suggest generating a new project and adding one thing at a time from an existing application to help determine what is and is not working.

**Comment by ryanvanderpol** [comment]
@brodybits I understand your point, but with a large project, that's easier said than done.  If that's what I have to do, I'd honestly just not use this repo at all because I just don't have the time to debug this stuff.  Switching to TVML is an option I would consider to avoid spending all this time debugging here.

@dlowder-salesforce happy to send you the code. I'll share a Dropbox link with the email address on your GitHub profile.

**Comment by dlowder-salesforce** [comment]
Hmm I just ran your project in the simulator, made a change or two and fast refresh worked without issue.  Does this issue only happen on real devices? Maybe you have some stale objects in the metro cache?

**Comment by ryanvanderpol** [comment]
Thanks for taking a look. I haven't tried on a real device yet, just the simulator. I've tried deleting the entire `node_modules` folder and cleaning the iOS build in xcode. How do I clear the metro cache?

**Comment by dlowder-salesforce** [comment]
I was not able to see any error before or after changing JS code.

Try `yarn start —reset-cache` when starting the packager.

**Comment by ryanvanderpol** [comment]
Thanks, but that didn't work.  If you're not seeing an error message, that is at least a bit encouraging because it seems like it's probably something in my environment.  Unfortunately, I'm just not sure how to proceed. For now I guess I'll just ignore it, since it doesn't seem to impact the app once I dismiss the message, but there's definitely something strange going on here.
