### ISSUE TITLE
Noob setup problem

### ISSUE THREAD

**Issue by oscadev** [react-native-community/react-native-tvos#37]
The instructions dont make sense to me. It says "do not install react native globally", which I didnt (I use npx react-native), byut then says to run:
"react-native init TestApp --version=react-native@npm:react-native-tvos@latest"
which would only work if react native is installed globally. 

Using npx, how do I create a tvos react native project?

**Comment by dlowder-salesforce** [comment]
Install `react-native-cli` globally. :)

I will clarify those in the docs.

**Comment by oscadev** [comment]
Thanks for the reply. Installing the cli solved all my issues. I thought npx was just a newer way to achieve the same, but it wasn’t working using npx.

**Comment by dlowder-salesforce** [comment]
@oscadev I will also document how to use npx with the newer `@react-native-community/cli` package.

**Comment by oscadev** [comment]
Thanks, that’d be great!
