### ISSUE TITLE
impossible to build/run after moving code to another folder

### ISSUE THREAD

**Issue by vgrafe** [react-native-community/react-native-tvos#38]
React Native version:
System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 24.83 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.4.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native-tvos:  0.61.5-0

## Steps To Reproduce

1. `react-native init TestApp --version=react-native@npm:react-native-tvos@latest`
2. `cd TestApp && react-native run-ios  --simulator "Apple TV" --scheme "TestApp-tvOS"` 
3. The app runs in the simulator!
4. rename the TestApp folder
5. using the same command, the app does not run. 
```bash
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening tv.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/vgrafe/Documents/code/tvasd/ios/build/tv-tvOS

note: Using new build system
note: Planning build
note: Constructing build description
CreateBuildDirectory /Users/vgrafe/Documents/code/tvasd/ios/build/tv-tvOS/Build/Products (in target 'Folly-tvOS' from project 'Pods')
    cd /Users/vgrafe/Documents/code/tvasd/ios/Pods
    builtin-create-build-directory /Users/vgrafe/Documents/code/tvasd/ios/build/tv-tvOS/Build/Products
```

Describe what you expected to happen:

I'd expect it to work. I know this sounds like a silly use case, but I'll explain how I found this: I am trying to build a monorepo with yarn workspaces to share code/components between TV apps and other platforms. For some reason, I have the exact same error when initializing the project in the workspace folder! So weird. So I decided to init in an external folder and then move the files. Then I found this issue.

Thanks for any help!

**Comment by vgrafe** [comment]
BTW - when trying to run a freshly init RN-TV project in the workspaces folder, the error is the same than the one above. Also, further down is something that seems like the relevant error: 
```bash
/Users/vgrafe/Documents/code/react-native-web-monorepo/packages/tv/ios/tv/AppDelegate.h:8:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by dlowder-salesforce** [comment]
I was able to reproduce this.... this is probably going to happen with projects using react-native core repo as well.

I fixed it by removing the `ios/build` folder after changing the name of the top level folder, then re-running `react-native run-ios`.  Does that help you?

**Comment by vgrafe** [comment]
Yes, good call. Following directions fix the problem. Now I have to investigate why this error happens when using yarn workspaces, but I am pretty sure this has to d with bad hoisting configuration.

**Comment by vgrafe** [comment]
Thank you! 😀

**Comment by dlowder-salesforce** [comment]
Glad that works!!! That folder is where Xcode caches compiled objects during `run-iOS`, and maybe the folder name change prevents the next build from finding cached objects and headers.

**Comment by ericlifs** [comment]
@vgrafe were you able to configure it properly for yarn workspaces? I'm having a lot of issues. Thanks!!

**Comment by vgrafe** [comment]
I gave up on workspaces, and at first configured metro to look into other folders, but still had issues. Now I use git submodules, which works perfectly, and allows all the things: click to definition, no bugs, etc etc.
