### ISSUE TITLE
click remote "menu" btn doesn't go back prev screen in navigation - exits app

### ISSUE THREAD

**Issue by TheoGit** [react-native-community/react-native-tvos#40]
I've developed a RN ATV app that uses react navigation; from my main menu if 

React Native version:
System:
    OS: macOS Mojave 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 3.64 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.0 - ~/.nvm/versions/node/v12.3.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native-tvos: 0.61.2-0 => 0.61.5-0

## Steps To Reproduce
1.  Click on the main menu of my app to navigate to another screen 
     => (navigation.navigate('groupsRoute');
2. Do some action on this screen, then click the "Menu" button on the Apple Remote
3. App is exited to Apple TV home screen.

Expected to navigate to the previous screen in the stack - NOT exit the app unless on Home screen.

Snack, code example, screenshot, or link to a repository:
The menu button click is not being captured by TVEventHandler - it just exits the app
    this._tvEventHandler.enable(this, (cmp, evt) => {
      if (evt.eventType === 'menu') {
        setRemoteMenuButtonPressed();
      }

**Comment by dlowder-salesforce** [comment]
You need to use the new `TVMenuControl` API.  It has methods to enable and disable the menu key. Enable it when a screen is pushed onto the stack, and then disable whenever you return to the home screen.

**Comment by TheoGit** [comment]
By "new" TVMenuControl - is this is a new/separate library or something; I've been using TVMenuControl since we created this app.
    this._tvEventHandler = new TVEventHandler();

Also, we wrap our app inside of a component (SiriRemote) which monitors menu actions for each page; so are you suggesting we now have to enable TVEventHandler page by page?
      <Provider store={store}>
        <**SiriRemote**>
            <Navigator />
        </**SiriRemote**>
      </Provider>

**Comment by keshavkaul** [comment]
@TheoGit 
`TVMenuControl` is imported from `react-native`

It has two methods ->
`disableTVMenuKey()`
`enableTVMenuKey()`

Like @dlowder-salesforce says, enable MenuKey to enable `BackHandler`, imported from `react-native`, to receive back events and disable MenuKey to disable `BackHandler` to receive back events.

FYI, `react-navigation` makes use of `BackHandler` to listen for back navigation events in a stack.

You just need to write the logic to enable or disable MenuKey based on the stack state.

**Comment by TheoGit** [comment]
@keshavkaul thanks I'm actually aware of those methods; however as I posted our app is wrapped inside a component that has set enableTVMenuKey() - we track menu actions throughout the app, many pages - it sounds like I will have to now unwrap that component and do this page by page, duplicating a lot code --- this will be a massive undertaking - I appreciate your input

**Comment by keshavkaul** [comment]
@TheoGit You mentioned using TVEventHandler, that's why I reiterated using TVMenuControl instead.

As for keeping this logic in one place,
In react-navigation, the App container component has a prop something like onNavigationChange callback.. I've used the router states in this callback to enable or disable menu key based on whether current state has a view stacked on top or not.

Goodluck!

**Comment by TheoGit** [comment]
@keshavkaul I will look into that - thank you
I'm using AppStack.router.getStateForAction = (action, state) => {}
The menu/esc button is bypassing all attempts to trap the event, I'll keep plugging

**Comment by TheoGit** [comment]
Figured it out - it works now - thanks!

**Comment by jeffreyabarrios** [comment]
> Figured it out - it works now - thanks!

How did you handle it? I'm facing a similar problem.

**Comment by crewtaylorfd** [comment]
I am having trouble with this. I am using `enableTVMenuKey` in the `useEffect` on mount of a component that I _don't_ want to exit from but just go back in the navigation stack. However, this is still causing the app to exit in that component.

**Comment by douglowder** [comment]
@crewtaylorfd if you can provide a sample app that reproduces your issue, I will take a look.
