### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by keshavkaul** [react-native-community/react-native-tvos#41]
I'm using Typescript in my project and was wondering if Typescript support is planned in the near future? I would like to help in this aspect. 

A good first step would be to document all the different TV-related API definitions and then work on adding Typescript support for each API. Thoughts?

**Comment by dlowder-salesforce** [comment]
I just had a look at https://facebook.github.io/react-native/docs/typescript for their recommendations on how to add Typescript support.

It looks like the right place to add definitions for TV-related React Native APIs would be here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native

This is the source for the @types/react-native NPM package, which is what FB recommends to use.

**Comment by Krisztiaan** [comment]
If you're using `patch-package`, you can grab [my patch for `@types/react-native-tvos`](https://gist.github.com/Krisztiaan/11856c0faffc70f00766b7f791375a75). I'll look into how it'd be best to add this to `DefinitelyTyped`

**Comment by olafurnsig** [comment]
Upvotes for typescript support!

**Comment by dlowder-salesforce** [comment]
@Krisztiaan thanks VERY much for your patch.  Sorry for the delay in responding here.  If there is anything I can do to help, please let me know.

**Comment by Krisztiaan** [comment]
No, thanks, I'm getting my feet wet with `DefinitelyTyped` and seeing how this'd be best implemented. Probably similar as this repo.

**Comment by Krisztiaan** [comment]
Will update for 63 once we ourselves have done the upgrade too :)

**Comment by Krisztiaan** [comment]
@dlowder-salesforce I'm wondering if an `index.d.ts` file like [this one](https://gist.github.com/Krisztiaan/3d24c7a3c3d4dd8d206c12903adc61d7) would make sense in this repo, so we'd have a lot more flexibility, and a ready to use solution.

**Comment by dlowder-salesforce** [comment]
@Krisztiaan thanks for the PR, looks great!  I'll try making an example TS project that includes most of the TV types.
