### ISSUE TITLE
iOS Dictation TextInput ends abruptly between words (0.59 and npm:react-native-tvos@0.61.5-0)

### ISSUE THREAD

**Issue by Mahigoli** [react-native-community/react-native-tvos#42]
Using dictation mode on a TextInput in iOS works partially. It only writes 1 word down then the dictation ends. (on react-native apple tv)

I am using react-native for apple tv and I tried with 0.59.9
xcode 11.3

it only grabs one word. I tried the debounce from
#18890 and it didn't help. However, when I am **in debug mode it works fine** so I think something is wrong with the timeline issue.

Try using iOS dictation in the TextInput. Be sure to use a long sentence...

Expected Behavior
I expect the TextInput to capture the entire dictation.

Actual Behavior
The dictation will end abruptly between words.

**Comment by dlowder-salesforce** [comment]
Is this happening on both iOS and tvOS?  Does this happen with 0.61.5-0?

**Comment by Mahigoli** [comment]
It happens only on tvOS and on both 0.61.5-0 and react-native 0.59.9.

**Comment by dlowder-salesforce** [comment]
@Mahigoli thanks for the info.  Can you put up a repo with a simple RN app that demonstrates the problem, and also includes the debounce that you tried?  Once I have that I will start actively working on this.

**Comment by Mahigoli** [comment]
import _ from 'lodash'

class SomeComponent extends React.Component {
  
  constructor(props){
    super(props);
    this.state = {
      text: ''
    }
    this.onChangeTextDelayed = _.debounce(this.onChangeText.bind(this), 1500)
  }
  
  onChangeText(text) {
    this.setState({text})
  }

  render() {
    return (
      <TextInput
        onBlur={()=>{
          this.onChangeTextDelayed.flush()
        }}
        onChangeText={this.onChangeTextDelayed}
        value={this.state.text}
      />
    )
  }
}

**Comment by Mahigoli** [comment]
Hi @dlowder-salesforce  is this enough information?

**Comment by dlowder-salesforce** [comment]
Yes this should do it.... I’ll try on different simulators and devices and see what happens

**Comment by Mahigoli** [comment]
Thanks, I did try it with connecting actual apple tv device in debug mode it worked and when I built and installed ipa it didn't work.

**Comment by dlowder-salesforce** [comment]
@Mahigoli I looked through https://github.com/facebook/react-native/issues/18890 and compared it to latest 0.61.5 code.  The real problem is the way attributed text is set during dictation.  There are fixes in place for iOS, but they don't work for tvOS.

I have a quick fix that works for now, eliminating the need for the debounce or the onBlur method: https://github.com/react-native-community/react-native-tvos/commit/99db0cebdfe811f5d77e51bd4b29241ffcb70d79

Can you test the above and let me know if it creates any issues or regressions for you?

**Comment by Mahigoli** [comment]
Thanks @dlowder-salesforce. It did work with 0.61.5.

**Comment by dlowder-salesforce** [comment]
I would add the fix as a patch in the npm postinstall step in your prod repo.... I’ll go ahead and get this fix into the next react-native-tvos release.

**Comment by Mahigoli** [comment]
This is a great idea! Thanks @dlowder-salesforce I will do that.

**Comment by dlowder-salesforce** [comment]
This is merged, and appears in https://github.com/react-native-community/react-native-tvos/releases/tag/v0.61.5-1 .  Closing.
