### ISSUE TITLE
tvOS: Already focused Touchable Components keeps increasing in size when TVFocusGuide destinations points to it

### ISSUE THREAD

**Issue by keshavkaul** [react-native-community/react-native-tvos#51]
Reference View Layout ->
https://developer.apple.com/documentation/uikit/focus-based_navigation/creating_custom_navigation_interactions

Please see the above reference to understand the view layout and will help in reproducing the issue:

If focus is on button 4, and we move right where the focus guide is present, the focus loops through the already focused button 4 and the size of button 4 keeps increasing the more we swipe right towards the focus guide.

**Comment by dlowder-salesforce** [comment]
This is very interesting... I will try to reproduce this and see if there is a way to fix it.

**Comment by keshavkaul** [comment]
@dlowder-salesforce 
The issue can be fixed in the `didUpdateFocus` method ->

https://github.com/react-native-community/react-native-tvos/blob/master/React/Views/RCTTVView.m#L200

we just need to check if the previously focused view is the same as the next focused view and not proceed further with sending focus events / adding animation effects.

I modified the code and saw that it is working as expected (no increase in size)

**Comment by dlowder-salesforce** [comment]
If you have a fix already, I'd really appreciate it if you submit a PR against the tvos-v0.61.5 branch :)

**Comment by keshavkaul** [comment]
@dlowder-salesforce I've created the PR #60 
Let me know your thoughts

**Comment by dlowder-salesforce** [comment]
#60 is merged, and appears in release https://github.com/react-native-community/react-native-tvos/releases/tag/v0.61.5-1 . Closing.
