### ISSUE TITLE
Custom Fonts are not added to the Info.plist in the tvOS target

### ISSUE THREAD

**Issue by ryanvanderpol** [react-native-community/react-native-tvos#59]
This issue was previously reported in the core React Native repository here: [Custom fonts won't load on tvOS apps - Unrecognized font family #18025](https://github.com/facebook/react-native/issues/18025).  

Took me hours and hours to figure out what was going on, but a comment in that issue thread led me to figure out that the `Info.plist` for my `-tvos` target did not get the fonts added to it after adding them to my assets and running `react-native link`.

React Native version:
```
% react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 706.13 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-23 | Android TV Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native-tvos:  0.61.5-0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Follow the instructions in [Adding custom fonts in react native 60+](https://github.com/facebook/react-native/issues/25852)
2. Reference your custom font anywhere in your app and run the `tvOS` target.  You will receive an `Unrecognized font family` error message.
3. Run the NON-tvos target and it will work fine.
4. Compare `Info.plist` from `ios/TestApp` with the `Info.plist` in `ios/TestApp-tvOS`.  You'll notice your fonts are missing.

**Comment by dlowder-salesforce** [comment]
This is actually an issue in the CLI, not in the react-native-tvos repo.  So it would have to be fixed in https://github.com/react-native-community/react-native-cli.  Right now, the code there seems to be just getting the first target in the project (the iOS one), and ignoring the tvOS one.
