### ISSUE TITLE
integration with react-native-video, missing React headers

### ISSUE THREAD

**Issue by jerrolb** [react-native-community/react-native-tvos#79]
Hi, I'd like to implement video playback in my TVOS app. I used react-native-tvos to init a project then runs in the apple TV simulator. I npm installed react-native-video which requires manually linking RCTVideo.a in Xcode. However, after adding it, the build fails with missing React headers. For example `React/RCTViewManager.h file not found in RCTVideoManager.m`.

I don't think it's necessarily an issue with this repo, just wondering if anybody has had similar issues or knows how to fix. Maybe this repo needs to be synced with newest react-native?

I have added custom header search paths, unchecked paralellize build and added React in custom build order, tried editing podfile, different versions ,etc.

Any help or even another good video playback solution appreciated.

**Comment by dlowder-salesforce** [comment]
I would not try to manually link the binary.... apps using current and recent versions of React Native should use Cocoapods to bring in dependencies like react-native-video.

See this example project: https://github.com/dlowder-salesforce/RNAppleTVTalk

In particular, look at `package.json` and `iOS/Podfile`.

**Comment by jerrolb** [comment]
Thanks for the quick reply. You have a tvOS project using react-native-video... awesome!! 

I think I was just missing the line that adds react-native-video as a pod in the Podfile? I've added and reinstalled pods.

I'm getting black screen for the <Video> component, but idk if it's a build issue, my environment, my code or a bug at this point. I'll keep digging. If nothing else I should be able to reference your Apple TV talk project to figure it out.

Thanks for this repo, I've almost got a fully functional video streaming app!

**Comment by dlowder-salesforce** [comment]
Great to hear -- good luck with the app :)
