### ISSUE TITLE
Question: Is there a way of working on localhost on Apple TV?

### ISSUE THREAD

**Issue by nriccar** [react-native-community/react-native-tvos#80]
Hello, I have searched for this and found no luck. Is there a way of react-native run ios on the real apple tv?

Thanks

**Comment by dlowder-salesforce** [comment]
For simulator you would do

```
react-native run-ios  --simulator "Apple TV" --scheme "TestApp-tvOS"
```

For device,

```
react-native run-ios  --device "nriccars TV" --scheme "TestApp-tvOS"
```

This will only work if you have customized your Xcode project to add your developer credentials, profiles, etc.

**Comment by nriccar** [comment]
Thank you @dlowder-salesforce.

`This will only work if you have customized your Xcode project to add your developer credentials, profiles, etc.

`

What do you mean by this?

**Comment by dlowder-salesforce** [comment]
In order to run an iOS or tvOS app on a real device, you need to sign the app using your Apple developer credentials.  The process for React Native apps is documented at https://reactnative.dev/docs/running-on-device

**Comment by nriccar** [comment]
Don't know how I didn't saw that one. Expected to be more difficult, but yes, you can just plug it as a Device to your computer and run on localhost.

Thank you @dlowder-salesforce
