### ISSUE TITLE
InputText broken in Android TV?

### ISSUE THREAD

**Issue by ApWin** [react-native-community/react-native-tvos#99]
InputText doesn't work for React Native 0.62.2

**Comment by dlowder-salesforce** [comment]
Please provide a more detailed description.

- What specifically is not working in InputText?
- What tvOS version did you test against?
- Please provide sample code that shows the issue

**Comment by ApWin** [comment]
Hi @dlowder-salesforce  First of all Thanks for your Supporting react-native-tvos. I'm using react-native-tvos for create android TV. On the react native documentation for tv app building ( https://reactnative.dev/docs/building-for-tv ), noted that :  "InputText components do not work for now (i.e. they cannot receive focus)." So what other option is there to use TextInput ?

react-native-tvOS: 0.62.2
react: 16.11

**Comment by dlowder-salesforce** [comment]
It is working in 0.63.1-1 (latest release). There were focus fixes done in https://github.com/react-native-community/react-native-tvos/pull/89

**Comment by ApWin** [comment]
@dlowder-salesforce  Is it possible to fix it in version 0.62.2. Because of 0.63.1-1 version of react native tvOS doesn't support for IOS 12.2 version apple TV  ???

**Comment by mehthabux** [comment]
@ApWinn please follow the file changes in #89 .

**Comment by Krisztiaan** [comment]
@ApWin it should support tvOS 12, and as far as I can tell, there's not enough capacity to maintain multiple different versions of this library.

**Comment by ApWin** [comment]
Okay, Thanks for All ))

**Comment by dlowder-salesforce** [comment]
See also #97 , where there is a discussion of the fixes done to support tvOS 12.x.  Those fixes are not in 0.62.2-x, so you should definitely move to the latest release :)
